sudo: required
services:
  - docker
  
before_install:
  - docker build -t medrahim/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true medrahim/react-test npm test

after_success:
  - docker build -t medrahim/multi-client ./client
  - docker build -t medrahim/multi-nginx ./nginx
  - docker build -t medrahim/multi-server ./server
  - docker build -t medrahim/multi-worker ./worker
# login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
# push to docker hub
  - docker push medrahim/multi-client
  - docker push medrahim/multi-nginx
  - docker push medrahim/multi-server
  - docker push medrahim/multi-worker


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-527654417117"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

